## Without using pipeline

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer         # we have some missing values 
from sklearn.preprocessing import OneHotEncoder  # we have categorical data
from sklearn.preprocessing import MinMaxScaler   # for scaling
from sklearn.tree import DecisionTreeClassifier  # for making predictions

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day29-sklearn-pipelines/train.csv')
df.head(4)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S

In [3]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [4]:
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)
df.head(5)

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [5]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [6]:
# you can fill nan values with this or you can use SimpleImputer
#df.Age = df.Age.fillna(df.Age.median())
#df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

In [7]:
df.sample(10)

Survived  Pclass     Sex   Age  SibSp  Parch      Fare Embarked
525         0       3    male  40.5      0      0    7.7500        Q
687         0       3    male  19.0      0      0   10.1708        S
625         0       1    male  61.0      0      0   32.3208        S
348         1       3    male   3.0      1      1   15.9000        S
6           0       1    male  54.0      0      0   51.8625        S
188         0       3    male  40.0      1      1   15.5000        Q
101         0       3    male   NaN      0      0    7.8958        S
581         1       1  female  39.0      1      1  110.8833        C
118         0       1    male  24.0      0      1  247.5208        C
599         1       1    male  49.0      1      0   56.9292        C

In [26]:
# train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Survived']),
                                                    df.Survived,
                                                    test_size=.3,
                                                    random_state=42)

In [27]:
X_train.head(4)

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
445       1    male   4.0      0      2  81.8583        S
650       3    male   NaN      0      0   7.8958        S
172       3  female   1.0      1      1  11.1333        S
450       2    male  36.0      1      2  27.7500        S

In [28]:
y_train.head(4)

445    1
650    0
172    1
450    0
Name: Survived, dtype: int64

In [29]:
 # Applying imputation to fill nan values

si_age = SimpleImputer()
si_embarked = SimpleImputer(strategy='most_frequent')

# fit and tranform x_train
X_train_age = si_age.fit_transform(X_train[['Age']])
X_train_embarked = si_embarked.fit_transform(X_train[['Embarked']])

# transform x_test
X_test_age = si_age.transform(X_test[['Age']])
X_test_embarked = si_embarked.transform(X_test[['Embarked']])

In [30]:
X_train_embarked

array([['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['Q'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['Q'],
       ['C'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
      

In [31]:
# nan values replaced in X_train and X_test
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [32]:
# one hot encoding Sex and Embarked

ohe_sex = OneHotEncoder(sparse=False,handle_unknown='ignore')
ohe_embarked = OneHotEncoder(sparse=False,handle_unknown='ignore')

X_train_sex = ohe_sex.fit_transform(X_train[['Sex']])
X_train_embarked = ohe_embarked.fit_transform(X_train_embarked)

X_test_sex = ohe_sex.transform(X_test[['Sex']])
X_test_embarked = ohe_embarked.transform(X_test_embarked)

In [33]:
X_train_embarked

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [34]:
X_train.head(4)

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
445       1    male   4.0      0      2  81.8583        S
650       3    male   NaN      0      0   7.8958        S
172       3  female   1.0      1      1  11.1333        S
450       2    male  36.0      1      2  27.7500        S

In [35]:
X_train_rem = X_train.drop(columns=['Sex','Age','Embarked'])

In [36]:
X_test_rem = X_test.drop(columns=['Sex','Age','Embarked'])

In [37]:
X_train_transformed = np.concatenate((X_train_rem,X_train_age,
                                      X_train_sex,X_train_embarked),axis=1)
X_test_transformed = np.concatenate((X_test_rem,X_test_age,
                                     X_test_sex,X_test_embarked),axis=1)

In [38]:
X_train_transformed

array([[1., 0., 2., ..., 0., 0., 1.],
       [3., 0., 0., ..., 0., 0., 1.],
       [3., 1., 1., ..., 0., 0., 1.],
       ...,
       [3., 2., 0., ..., 0., 0., 1.],
       [1., 1., 2., ..., 0., 0., 1.],
       [1., 0., 1., ..., 0., 0., 1.]])

In [39]:
X_test_transformed.shape

(268, 10)

In [40]:
clf = DecisionTreeClassifier()
clf.fit(X_train_transformed,y_train)

DecisionTreeClassifier()

In [41]:
y_pred = clf.predict(X_test_transformed)
y_pred

array([0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0])

In [42]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7350746268656716

In [43]:
import pickle

In [47]:
pickle.dump(ohe_sex,open('ohe_sex.pkl','wb'))
pickle.dump(ohe_embarked,open('ohe_embarked.pkl','wb'))
pickle.dump(clf,open('clf.pkl','wb'))

## Predict without pipeline

In [48]:
import pickle
import numpy as np
import pandas as pd

In [49]:
# loading models
ohe_sex = pickle.load(open('/content/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('/content/ohe_embarked.pkl','rb'))
clf = pickle.load(open('/content/clf.pkl','rb'))

In [50]:
# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [56]:
test_input[:,1]

array(['male'], dtype=object)

In [51]:
# we have to perform OheHotEncoding here also
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))
test_input_sex

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  "X does not have valid feature names, but"


array([[0., 1.]])

In [52]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))
test_input_embarked

array([[0., 0., 1.]])

In [53]:
test_input_age = test_input[:,2].reshape(1,1)

In [54]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)
test_input_transformed.shape

(1, 10)

In [55]:
clf.predict(test_input_transformed)

array([1])

In [ ]:
# tried

In [57]:
test__train = np.array([1, 'male',	4.0,	0,	2,	81.8583,	'S'],dtype=object).reshape(1,7)
test__train

array([[1, 'male', 4.0, 0, 2, 81.8583, 'S']], dtype=object)

In [67]:
test__train[:,1]

array(['male'], dtype=object)

In [68]:
test_train_sex = ohe_sex.transform(test__train[:,1].reshape(1,1))
test_train_sex

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  "X does not have valid feature names, but"


array([[0., 1.]])

In [69]:
test_train_embarked = ohe_embarked.transform(test__train[:,-1].reshape(1,1))
test_train_embarked

array([[0., 0., 1.]])

In [70]:
test_train_age = test__train[:,2].reshape(1,1)

In [72]:
final = np.concatenate((test__train[:,[0,3,4,5]],test_train_age,
               test_train_sex,test_train_embarked), axis=1)
final

array([[1, 0, 2, 81.8583, 4.0, 0.0, 1.0, 0.0, 0.0, 1.0]], dtype=object)

In [73]:
clf.predict(final)

array([1])